#!/usr/bin/env bash
# Google OAuth Setup Helper Script
# Project: tibia-hunts-app

echo "🔧 Google OAuth Setup Helper"
echo "============================"
echo ""
echo "✅ APIs already enabled:"
echo "   - Google+ API (plus.googleapis.com)"
echo "   - Identity Toolkit API (identitytoolkit.googleapis.com)"
echo "   - IAM Credentials API (iamcredentials.googleapis.com)"
echo ""
echo "📋 Next steps to complete OAuth setup:"
echo ""
echo "1. The Google Cloud Console should be open at:"
echo "   https://console.cloud.google.com/apis/credentials?project=tibia-hunts-app"
echo ""
echo "2. Click '+ CREATE CREDENTIALS' → 'OAuth 2.0 Client IDs'"
echo ""
echo "3. If prompted, configure OAuth consent screen first:"
echo "   - Application type: External"
echo "   - App name: TibiaHunts"
echo "   - User support email: your-email@gmail.com"
echo "   - Developer contact: your-email@gmail.com"
echo ""
echo "4. Create OAuth 2.0 Client ID:"
echo "   - Application type: Web application"
echo "   - Name: TibiaHunts Local Development"
echo "   - Authorized redirect URIs: http://localhost:8000/accounts/google/login/callback/"
echo ""
echo "5. Copy the credentials and run the update script:"
echo "   ./update-env-credentials.ps1"
echo ""
echo "🚀 After setup, test with: python src/manage.py runserver 8000"
