name: PR Title Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title Format
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .+$'
          allowed_prefixes: 'feat,fix,docs,style,refactor,perf,test,build,ci,chore,revert'
          prefix_case_sensitive: false
          min_length: 10
          max_length: 120
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR if title is invalid
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ **PR Title Format Error**

              Your PR title doesn't follow the conventional commit format required for semantic-release.

              **Required format:** \`type(scope): description\`

              **Valid types:** feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert

              **Examples:**
              - \`feat: add user authentication\`
              - \`fix(auth): resolve login redirect issue\`
              - \`docs: update API documentation\`
              - \`chore(deps): update dependencies\`

              **Current title:** "${context.payload.pull_request.title}"

              Please update your PR title to match the required format.`
            })
