name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # Use a PAT that can bypass branch protection rules
        token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    # Cache semantic-release and all its plugins globally installed
    # NOTE: If you change the plugin versions in the install step below,
    # you need to manually invalidate this cache by changing the cache key
    # (e.g., add a version suffix like semantic-release-v2-${{ runner.os }})
    - name: Cache semantic-release installation
      id: cache-semantic-release
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          /usr/local/lib/node_modules/semantic-release
          /usr/local/lib/node_modules/@semantic-release
        key: semantic-release-v1-${{ runner.os }}
        restore-keys: |
          semantic-release-v1-${{ runner.os }}

    - name: Install semantic-release and plugins
      if: steps.cache-semantic-release.outputs.cache-hit != 'true'
      run: |
        npm install -g semantic-release@21 @semantic-release/changelog@6 @semantic-release/git@10 @semantic-release/github@9 @semantic-release/exec@6 conventional-changelog-conventionalcommits@7

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
      run: npx semantic-release
